### ISSUE TITLE
"add training" generates a error because of missing mandatory fields

### ISSUE THREAD

**Issue by mighty-mj** [flkoch/training_planner#1]
Hi, 
firt, nice tool! :) 
I've just seen, that with the new training form, there is a small bug because there are not all mandatory fields shown. I've created a little patch for it, local it's working fine.

[bugfix_createTraining.patch.txt](https://github.com/flkoch/training_planner/files/4626888/bugfix_createTraining.patch.txt)

I'll investigate it a bit further and maybe use it for our club :)

Cheers

**Comment by mighty-mj** [comment]
sorry, i pasted the wrong patch in it, firstly i just ignored the field, but i think its better to show the field ;)
[bugfix_createTraining.patch.txt](https://github.com/flkoch/training_planner/files/4627202/bugfix_createTraining.patch.txt)

**Comment by flkoch** [comment]
Thanks for your comment and sorry for taking this long to come back.
I noticed this issue as well and have resolved  in 4214570
Hope this will help.
