### ISSUE TITLE
Member Registration with empty initials

### ISSUE THREAD

**Issue by mighty-mj** [flkoch/training_planner#2]
If a person signs-up with empty initials, one should insert the string to the initial field, not bind the method. see attached patch:

[bugfix_memberregistration_initials.patch.txt](https://github.com/flkoch/training_planner/files/4627835/bugfix_memberregistration_initials.patch.txt)

somehow, i can't create a branch to create a pull request... sorry :)

**Comment by flkoch** [comment]
Thanks for the feedback. This issue was resolved in ab7abe7
